---
name: FabForce-DBDesigner4-DBIC
version: 0.05
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: create DBIC scheme for DBDesigner4 xml file
license: perl
requires:
  FabForce::DBDesigner4: 0.09
  File::Spec: 3.12
build_requires:
  Carp: 0
  Test::CheckManifest: 1
  Test::More: 0
provides:
  FabForce::DBDesigner4::DBIC:
    file: lib/FabForce/DBDesigner4/DBIC.pm
    version: 0.05
generated_by: Module::Build version 0.26
