---
abstract: 'create DBIC scheme for DBDesigner4 xml file'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FabForce-DBDesigner4-DBIC
requires:
  Carp: 0
  FabForce::DBDesigner4: 0
  File::Basename: 0
  File::Spec: 0
  Test::More: 0
version: 0.10
